package:
  name: fsttrpglifepath
  version: 0.0.1

build:
 number: 1
 string: alpha

source:
  git_url: https://github.com/Krypticdator/FSTTRPGLifepath.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: description